apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: apiserver
    namespace: project-openshift-io
- apiVersion: v1
  kind: Service
  metadata:
    name: api
    namespace: project-openshift-io
  spec:
    ports:
    - port: 443
      protocol: TCP
      targetPort: 443
    selector:
      apiserver: "true"

- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: apiserver
    namespace: project-openshift-io
    labels:
      apiserver: "true"
  spec:
    template:
      metadata:
        labels:
          apiserver: "true"
      spec:
        containers:
        - name: apiserver
          image: openshift/origin-kube-projects:latest
          imagePullPolicy: IfNotPresent
          command:
          - "/kube-projects"
          - "--audit-log-path=-"
          - "--v=8"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 443
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 443
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 443
        serviceAccountName: apiserver

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.project.openshift.io
  spec:
    group: project.openshift.io
    version: v1
    service:
      namespace: project-openshift-io
      name: api
    insecureSkipTLSVerify: true
    groupPriorityMinimum: 10000
    versionPriority: 1
